# Generated by Django 4.2.10 on 2024-03-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_configuration',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='loan_configuration', to='loans.loanconfiguration'),
            preserve_default=False,
        ),
    ]
