# Generated by Django 4.2.10 on 2024-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_loan_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
